### ISSUE TITLE
tooltip line placement incorrect with null values

### ISSUE THREAD

**Issue by pwc1011** [gwatts/jquery.sparkline#22] opened 2012-07-10 21:04 UTC
We use a line graph to display values over time. Because we display over time, we use null values where there is no reading for a day. When there are null values, the tool tip value appears to display correctly, but the "red line" displays right of where it should display.

**Comment by gwatts** [comment] 2012-08-26 23:52
Duplicate of issue 4 (please reopen if I'm mistaken) now fixed in master

**Closed as completed by gwatts** 2012-08-26 23:53 UTC
Labels: duplicate
