### ISSUE TITLE
add bower

### ISSUE THREAD

**Issue by gbelmm** [gwatts/jquery.sparkline#130] opened 2014-10-14 21:14 UTC
add bower file please

**Comment by mantask** [comment] 2014-10-25 10:55
At least please add a compiled version (`jquery.sparkline.js`) to `/dist` folder

**Comment by mryellow** [comment] 2014-11-14 23:15
Yeah without a compiled version can't use bower to install the complete repo.

Takes 5mins to setup, saves everyone time.

**Comment by gwatts** [comment] 2014-11-14 23:25
Dupe of #77

**Closed as completed by gwatts** 2014-11-14 23:25 UTC
